services:
  - name: aura-frontend
    type: web
    env: node
    plan: starter
    branch: main
    autoDeploy: true
    root: next-app
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://aura-backend.onrender.com
    healthCheckPath: /

  - name: aura-backend
    type: web
    env: node
    plan: starter
    branch: main
    autoDeploy: true
    root: server
    buildCommand: npm install && PRISMA_SCHEMA=./prisma/schema.postgres.prisma npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase: "aura-db"
      - key: JWT_SECRET
        generator: "secret"
      - key: FRONTEND_ORIGIN
        value: "https://aura-frontend.onrender.com"
      - key: NODE_ENV
        value: "production"
      - key: UPLOAD_DIR
        value: "/data/uploads"
    healthCheckPath: /health

databases:
  - name: aura-db
    plan: starter
    databaseName: aura
